sonar.organization=3-fase-fiap-soat-team
sonar.projectKey=3-fase-fiap-soat-team_fiap-soat-application-produtos
sonar.projectName=fiap-soat-application-produtos

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.sourcesEncoding=UTF-8

sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/*.spec.ts
